### ISSUE TITLE
pip install ?

### ISSUE THREAD

**Issue by AdrienLemaire** [byCedric/swaglint#1]
Has the package been accidentally removed from Pypi ?

**Comment by byCedric** [comment]
Hi @Fandekasp,

No this package was not removed from pip, but neither was it added to pip 😉 This package is a JavaScript package, built in TypeScript, and added to the NPM repository. You can still install this package by using either [NPM](https://www.npmjs.com/get-npm) or [Yarn](https://yarnpkg.com/en/docs/install):

```
$ npm install -g swaglint
```

**Comment by AdrienLemaire** [comment]
hmm... sorry about that, must have been tired, couldn't even read your README properly.
Thanks for the quick follow-up though, cheers!

**Comment by byCedric** [comment]
No worries! Happy to help!
